config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'   #root 'pages#home'
  get "about" => "pages#about"    # create about_path

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_file_name:image, :matches => [/png\Z/, /jpg\Z/, /jpe?g\Z/, /gif\Z/]
  
  validates :image, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => {:within => 8..40},
                        :on => :create,
                        #:format => {:with => /\A.*(?=.{10,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\@\#\$\%\^\&\+\=]).*\Z/ }
                        :format => {:with => /\A.*(?=.{08,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*\Z/ }
                        
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true
         
  has_many :pins, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /pins
  # GET /pins.json
  def index
     # @pins = Pin.all # original
     
     #active record query - created_at descending order.
     @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
      
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    #Original
    #@pin = Pin.new
    
    #Build a new pin with the userID set from the current user
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    #Original
    #@pin = Pin.new(pin_params)

    #Build a new pin with the userID set from the current user
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end 
  
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">     <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">     <!-- NavBar -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to "pinteresting", root_path %></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_path %></li>
        <!-- Show a signin or logout as appropriate -->
        <% if user_signed_in? %>
            <li>
              <%= link_to new_pin_path do %>
                <span class="glyphicon glyphicon-plus"></span> New Pin
              <% end %>
            </li>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %> <!-- logic for user session -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
 
    <%= yield %>
  </div>
  
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron">
  <h1>Welcome</h1>
  <p>Spicy jalapeno bacon ipsum dolor amet jowl dolor eu andouille turducken ribeye adipisicing meatloaf burgdoggen labore. Aliqua salami in hamburger pork chop dolore. Ut prosciutto in boudin, pariatur est dolore. Excepteur ut ham short loin ad laborum pork loin meatball short ribs. Ham et velit tenderloin beef ribs. Lorem turducken meatball, duis bresaola meatloaf fugiat ut mollit tri-tip tempor pig minim.
</p>

    <!== Prompt them to Login or SignUp -->
    <p></p>
    <p>
      <%= link_to "Log in", new_user_session_path,  class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </p>
</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Spicy jalapeno bacon ipsum dolor amet deserunt est tail consequat shank beef ribs kielbasa bacon eu corned beef fugiat. Cupidatat exercitation officia doner anim alcatra aute shoulder pastrami reprehenderit elit proident fugiat id. Pork loin reprehenderit commodo, fatback ut fugiat cow kielbasa aute. Ribeye prosciutto chicken, sed hamburger id tempor shankle pork chop excepteur boudin dolore. Chuck exercitation consequat ground round rump pork loin ut ut. Aliqua tongue burgdoggen ut duis nulla rump boudin veniam enim adipisicing tempor.</p>
<p>Proident capicola meatloaf flank fatback. Short loin dolor irure jerky. Biltong ut aliqua meatball pork belly frankfurter. Pork chop ipsum turkey ea, veniam ut elit turducken ut beef in ullamco. Lorem in laboris cillum tri-tip biltong shoulder aliquip eiusmod. Nisi ex porchetta beef ribs consectetur ham hock turkey chuck nulla. Minim quis landjaeger deserunt sed pastrami turducken cow ut tempor.</p>
<p>Shankle andouille commodo pariatur exercitation aliquip duis consequat ipsum salami sint pancetta biltong tri-tip filet mignon. Eu venison ut lorem occaecat, alcatra shank laborum swine consequat turkey. Porchetta beef ribs mollit, laboris biltong chuck cupim flank consequat reprehenderit ad eu. Anim andouille eu, t-bone swine ground round ham hock salami exercitation cillum brisket dolore enim chuck. Cupim tri-tip duis, ut chuck leberkas pork belly pastrami shankle ad irure brisket. Consequat flank ball tip laborum.</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome</h1>
  <p>Spicy jalapeno bacon ipsum dolor amet jowl dolor eu andouille turducken ribeye adipisicing meatloaf burgdoggen labore. Aliqua salami in hamburger pork chop dolore. Ut prosciutto in boudin, pariatur est dolore. Excepteur ut ham short loin ad laborum pork loin meatball short ribs. Ham et velit tenderloin beef ribs. Lorem turducken meatball, duis bresaola meatloaf fugiat ut mollit tri-tip tempor pig minim.
</p>

  <% if user_signed_in? %>
    <!== do something for our signed in users -->
    <p></p>  
    <p>Thanks for signing in :-)</p>    
  <% else %>
    <!== Prompt them to Login or SignUp -->
    <p></p>
    <p>
      <%= link_to "Log in", new_user_session_path,  class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </p>
  <% end %>  <!== user_sign_in block -->
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<!-- Render the pages/home _home.html.erb partial if the user isnt logged in. -->
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>

        <!-- If current_user (logged in) AND && also owner of the pin-->
        <% if current_user && pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
            
            </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div> 

<!-- Display pagination links for the user -->
<!-- Wrapping in a div class to center, using bootstrap for styling -->
<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:large) %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>

        <!-- If current_user (logged in) AND && also owner of the pin-->
        <% if current_user && @pin.user == current_user %>
          <%= link_to edit_pin_path(@pin) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
          <% end %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>